# Generated by Django 5.2 on 2025-07-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_rename_created_at_user_created_time_user_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=8,
            ),
            preserve_default=False,
        ),
    ]
