# Generated by Django 5.2 on 2025-08-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_guid_user_updated_time_alter_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="full_name_uz",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
