# Generated by Django 5.2 on 2025-08-13 18:40

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_district_user_region"),
        ("common", "0003_page_content_ru_page_content_uz_page_title_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="district",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="region",
                chained_model_field="region",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.district",
            ),
        ),
    ]
