# Generated by Django 5.2 on 2025-07-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("icon", models.ImageField(upload_to="category_icons/")),
                (
                    "products_count",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
            ],
        ),
    ]
