# Generated by Django 5.2 on 2025-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="category_icons/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="products_count",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
