# Generated by Django 5.2 on 2025-07-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_category_options_alter_category_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_uz",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
