# Generated by Django 5.2 on 2025-08-01 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_category_name_ru_category_name_uz"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="products_count",
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child",
                to="store.category",
            ),
        ),
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_uz", models.CharField(max_length=100, null=True)),
                ("name_ru", models.CharField(max_length=100, null=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("description_uz", models.TextField(null=True)),
                ("description_ru", models.TextField(null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("is_liked", models.BooleanField(default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to="store.category",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="ad_photos/")),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="store.ad",
                    ),
                ),
            ],
        ),
    ]
