# Generated by Django 5.2 on 2025-08-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "store",
            "0004_remove_category_products_count_category_parent_ad_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="adphoto",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
