# Generated by Django 5.2 on 2025-08-02 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_adphoto_is_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="adphoto",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025,
                    8,
                    2,
                    16,
                    31,
                    52,
                    464068,
                    tzinfo=datetime.timezone.utc,
                ),
            ),
            preserve_default=False,
        ),
    ]
