# Generated by Django 5.2 on 2025-08-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_adphoto_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="views_count",
            new_name="view_count",
        ),
    ]
