# Generated by Django 5.2 on 2025-08-07 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_favouriteproduct_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favouriteproduct",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="favouriteproduct",
            name="device_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="favouriteproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "product"),
                name="unique_user_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="favouriteproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(("device_id__isnull", False)),
                fields=("device_id", "product"),
                name="unique_device_product",
            ),
        ),
    ]
