# Generated by Django 5.2 on 2025-07-09 10:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="created_at",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="updated_at",
            new_name="updated_time",
        ),
        migrations.AddField(
            model_name="page",
            name="guid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="working_hours_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="setting",
            name="working_hours_uz",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="district",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="district",
            name="name_uz",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="name_uz",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
