# Generated by Django 5.2 on 2025-07-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_rename_created_at_page_created_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="content_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="content_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="title_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="title_uz",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
